version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        BUILD_NUMBER: "${BUILD_NUMBER:-local}"
        GIT_COMMIT_SHORT: "${GIT_COMMIT_SHORT:-unknown}"
    environment:
      - BUILD_NUMBER=${BUILD_NUMBER:-local}
      - GIT_COMMIT_SHORT=${GIT_COMMIT_SHORT:-unknown}
    networks:
      - bg-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - API_URL=http://api:3000
    networks:
      - bg-network

networks:
  bg-network:
    external: true